let listaAutores = [{
    'nombre': 'Julio Serrano Echeverría',
    'nacimiento': '1983',
    'defuncion': '',
    'nacionalidad': 'Guatemalteco',
    'bibliografia': 'Poeta y artista multidisciplinario. Estudió Literatura en la Universidad de San Carlos de Guatemala, también cuenta con formación en cine y artes visuales.    Posteriormente completó su formación en España con una beca de la Fundación Carolina, en México con una beca de la Residencia para Artistas de Iberoamérica FONCA-AECID y de la Fundación Yaxs en Guatemala.    Fue uno de los fundadores en 2003 Festival Internacional de Poesía de Quetzaltenango. Dirigió el Festival Permanente de Poesía Xela 2003 y 2004. En 2008 fue fundador y coordinador del proyecto editorial www.librosminimos.org para promover libros de literatura contemporánea de autores centroamericanos y en 2013 una de las primeras editoriales guatemaltecas en ofrecer publicaciones de descarga libre en línea .  También ha sido editor literario en entidades como Editorial Cultura, del Ministerio de Cultura y Deportes y Editorial Piedra Santa, ambas en Guatemala.    En 2006 publicó su ópera prima en poesía, Las palabras y los días. y fue ganador del segundo lugar en el concurso de poesía Myrna Mack (2006).Desde entonces ha publicado varios libros de poesía, crónica y literatura infantil, Además publica periódicamente ensayos, crónicas y opinión en medios de la región',
    'libros': ['Desde las aguas', 'Desde los orígenes', 'Dos cabezas para meter un gol', 'En botas de astronauta', 'balam'],
    'imagenAutor': '/media/img/imgAutores/julio_serrano.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Guadalupe Castellanos',
    'nacimiento': '1966',
    'defuncion': '',
    'nacionalidad': 'Salvadoreña',
    'bibliografia': 'Nació en San Salvador, el 16 de febrero de 1966. Hija de Ricardo Castellanos y de Teresa Araujo de Castellanos. A la edad de trece años su familia se traslada a la ciudad de Santiago, Chile, donde cursa sus estudios de bachillerato. Estudió parvularia en la Universidad Católica de Chile, donde vivió durante su juventud. Regresa a El Salvador y estudia Ciencias de la Educación por la Universidad Evangélica de El Salvador, graduándose en 1991',
    'libros': ['La historia sin fin de Alissa', 'El monstruo en mi closet', 'El abrazo infinito', 'El semáforo de la ciudad de cristales'],
    'imagenAutor': '/media/img/imgAutores/guadalupe_castellanos.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Sergio Ramírez',
    'nacimiento': '1942',
    'defuncion': '',
    'nacionalidad': 'Nicaraguense',
    'bibliografia': 'Es el segundo de cinco hijos del matrimonio de Pedro Ramírez Gutiérrez y de la profesora de secundaria Luisa Mercado Gutiérrez. A los dieciocho años fundó la revista experimental Ventana junto con Fernando Gordillo escritor nicaragüense muerto en 1967, a los veintiséis años,con quien dirigió el movimiento literario Frente Ventana. En 1963 publicó su primer libro Cuentos, Editorial Nicaragüense, Managua y al año siguiente se graduó en Leyes por la Universidad Nacional Autónoma de León con «Medalla de Oro».    Se casó en 1964 con la socióloga Gertrudis Guerrero Mayorga. Ese año viajaron a Costa Rica, donde vivieron catorce años con un paréntesis de 1973 a 1975 en los que Ramírez se trasladó a Berlín con una beca otorgada por el Servicio de Intercambio Académico Alemán (DAAD) y escribió la novela ¿Te dio miedo la sangre? En Costa Rica dirigió la revista Repertorio y asumió la secretaría general del Consejo Superior Universitario Centroamericano (CSUCA) en aquel periodo con sede en ese país en dos oportunidades: 1968 y 1976. En 1978 fundó en San José la Editorial Universitaria Centroamericana (EDUCA). En diciembre de 2018 obtuvo la nacionalidad española por carta de naturaleza',
    'libros': ['Los pajaros que volaron', 'Togolele no sabe bailar', 'A la mesa con Rubén Dario', 'La jirafa embarazada', 'Sombras nada más'],
    'imagenAutor': '/media/img/imgAutores/sergio_ramirez.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Rubén Darío',
    'nacimiento': '1867',
    'defuncion': '1916',
    'nacionalidad': 'Nicaraguense',
    'bibliografia': 'Rubén Darío, cuyo verdadero nombre era Félix Rubén García Sarmiento, nació el 18 de Enero de 1867 en Metapa, Nicaragua. Hijo de Manuel García Darío y Rosa Sarmiento Darío.    Fue periodista y diplomático.    Estudió con los Jesuitas en 1878 y escribió en 1879 sus primeros poemas. Poesías y artículos en prosa fue un trabajo que realizó en 1881 y nunca llegó a publicar. Suspende sus estudios y luego se emplea en la Biblioteca Nacional de Managua en 1885.    En 1886 llegó a Valparaíso, tenía diecinueve años, allí realizó colaboraciones periodísticas en diarios de Valparaíso y Santiago. En 1888 aparecen sus Rimas y Azul. En Febrero del año siguiente parte a centroamérica pocos días después de haber enviado su primera colaboración al diario La Nación de Buenos Aires. En los años siguientes desempeña diversos cargos diplomáticos y publica en Madrid Cantos de vida y esperanza (1905) y El canto errante (1907). México, La Habana, París, Barcelona, son las escalas del viaje final de Darío. En Nueva York cae enfermo y se retira a una hacienda de Nicaragua. A las 10 de la noche del 6 de febrero de 1916 murió Darío a los 49 años de edad en León, la ciudad de su infancia. Frente a su distinguido cadáver de poeta desfilaron durante cinco días miles de personas.',
    'libros': ['Canción de otoño en primavera', 'Canción de la noche en el mar', 'El pájaro azul', 'la pesadilla de Honorio'],
    'imagenAutor': '/media/img/imgAutores/ruben_dario.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Pablo Antonio Cuadra',
    'nacimiento': '1912',
    'defuncion': '2002',
    'nacionalidad': 'Nicaraguense',
    'bibliografia': 'Poeta católico e ideólogo nicaragüense, nacido en Managua el 4 de noviembre de 1912, y fallecido el 2 de enero de 2002 en la misma capital. Una de las figuras más influyentes y prestigiosas de Nicaragua en las últimas décadas del siglo XX, al punto de ser habitualmente conocido por sus siglas: PAC. Hijo de Carlos Cuadra Pasos (1879-1964), jurista, estadista, canciller y diplomático, y de Merceditas Cardenal, su entorno familiar no es ajeno ni a la política ni a la poesía (entre sus familiares: José Coronel Urtecho y el presbítero Ernesto Cardenal, Ministro de Cultura cuando el régimen sandinista). De muy joven se incorporó como fundador al movimiento vanguardista de Nicaragua, en el que junto con José Coronel Urtecho mostró especial preocupación por los aspectos políticos e histórico culturales: sobre ellos ejerció muy temprana influencia Ramiro de Maeztu y la Defensa de la Hispanidad. Dirigió junto con Octavio Rocha la revista Vanguardia. Su abundante obra parte de los Poemas nicaragüenses, escritos entre 1930 y 1933 y publicados por la editorial Nascimento en Santiago de Chile en 1934. En 1936 se licencia en Leyes por la Universidad de Oriente y Mediodía (Granada, Nicaragua). Pero siendo todavía estudiante había tomado ya contacto con el grupo de monárquicos católicos que en la España de la República se habían organizado en torno a la revista Acción Española, de la que muy pronto sería colaborador:',
    'libros': ['Agosto', 'Cuentos escogidos', 'La segua', 'Los cuentos de tío Coyote y tío Conejo', 'Otro rapto de Europa', 'Siete árboles contra el atardecer'],
    'imagenAutor': '/media/img/imgAutores/cuadra_pablo_antonio.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Rowling, J.K.',
    'nacimiento': '1965',
    'defuncion': '',
    'nacionalidad': 'Británica',
    'bibliografia': 'La escritora británica Joanne Kathleen Rowling se hizo célebre con su serie de novelas dedicadas a las aventuras de Harry Potter, uno de los mayores fenómenos literarios de la historia. Las peripecias de un niño huérfano con poderes mágicos capaz de evadirse a voluntad a un mundo de fantasía consiguieron batir todos los récords de ventas en la literatura del género, aunque muchos críticos se mostraron reacios a encasillar los libros de Rowling como cuentos para niños, como ocurriera con el famoso Tom Sawyer de Mark Twain. La persona que hizo posible que muchos niños y adolescentes prefiriesen leer un libro a pasar las horas muertas delante del televisor es una tímida británica que se propuso escribir siete entregas de la serie, que equivalen a los cursos que el protagonista debe superar en la escuela de magia y hechicería a la que asiste cuando se escapa de la horrible realidad cotidiana en casa de sus mezquinos tíos.    Según algunos críticos literarios, la autora logró crear en sus novelas una inquietante atmósfera atractiva a los ojos de lectores de muy diversa condición y edad, a partir de influencias reconocibles en los libros de escritores británicos como Enid Blyton, Richmal Crompton o Roald Dahl. Pero, paradójicamente, ella misma afirmaba que nunca pretendió escribir fantasía y que la idea le surgió a partir de sus propios recuerdos de la infancia. Prácticamente desconocida y con problemas económicos en la primera mitad de la década de los noventa, cuando vivía de una modesta pensión como desempleada, J. K. Rowling se convirtió en una mujer rica y popular en Europa y sobre todo en Estados Unidos, donde multitudes de niños acompañados por sus padres soportarían largas colas en las librerías para hacerse con las últimas aventuras del pequeño mago.  ',
    'libros': ['Harry Potter y la piedra filosofal', 'Harry Potter y la cámara de los secretos', 'Harry Potter y el prisionero de Azkabán', 'Harry Potter y', 'Harry Potter y el caliz de fuego'],
    'imagenAutor': '/media/img/imgAutores/jk_rowling.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'J.R.R. Tolkien',
    'nacimiento': '1892',
    'defuncion': '1973',
    'nacionalidad': 'Británico',
    'bibliografia': 'Escritor británico de origen sudafricano mundialmente conocido como autor de El señor de los anillos (1954-1955), un verdadero clásico de la literatura fantástica. Aunque el autor ya era sobradamente conocido, en fechas recientes su obra ha alcanzado una difusión todavía mayor gracias a las adaptaciones cinematográficas de Peter Jackson. Hijo de padres ingleses, vivió en Sudáfrica hasta la muerte de su padre en 1896, año en que se trasladó con su familia a Inglaterra. La conversión de la madre al catolicismo lo marcó profundamente. Estudió en Oxford, y mostró muy pronto un vivo interés por la filología y las antiguas sagas y leyendas nórdicas. Tras participar en la Primera Guerra Mundial, enseñó primero lengua inglesa en la Universidad de Leeds. Profesor de lengua y literatura anglosajona en la Universidad de Oxford, se especializó en la época medieval.    Tras publicar algunos ensayos (Sir Gawain y el caballero verde, 1925; Beowulf, 1936), J. R. R. Tolkien inició la creación de una personal mitología inspirada en la saga artúrica y en la épica medieval anglosajona, plagada de elementos fantásticos y de seres y mundos imaginarios. Así, la novela El hobbit (1937) narra las vicisitudes de un pueblo apacible y sensato que vive en un mundo llamado Tierra media, junto con elfos, duendes y magos.    El hobbit fue el punto de partida de un ambicioso ciclo épico que se concretó en la trilogía de El señor de los anillos (1954-1955), dividida en tres volúmenes: La comunidad del anillo (1954), Las dos torres (1954) y El retorno del rey (1955). Dirigida a un público adulto, la obra de Tolkien encontró a mediados de la década de 1960 una gran acogida, hasta el extremo de convertirse en libro de culto y dar lugar a un género en alza, la «alta fantasía».    La actividad de J. R. R. Tolkien como novelista es inseparable de la del filólogo. Su goce intelectual por las lenguas antiguas (conocía el griego, el anglosajón, el medio inglés, el galés, el gótico, el finlandés, el islandés antiguo, el noruego antiguo, el alto alemán antiguo) lo llevaba a crear sonidos y a inventar lenguajes, siguiendo un método rigurosamente filológico. ',
    'libros': ['Roverandom', 'El Silmarillion', 'El Hobbit', 'La comunidad del anillo', 'Las dos torres', 'El retorno del Rey', 'La historia de la tierra Media', ],
    'imagenAutor': '/media/img/imgAutores/J._R._R._Tolkien.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Geroge R.R. Martin',
    'nacimiento': '1948',
    'defuncion': '',
    'nacionalidad': 'Estadounidense',
    'bibliografia': 'Es el mayor de tres hermanos. Creció en una familia trabajadora, su padre era estibador de ascendencia italo-germana, y su madre, de ascendencia irlandesa. Desde la infancia se interesó por la lectura y se convirtió en un precoz escritor de relatos. Posteriormente cursó estudios universitarios de periodismo en la Northwestern University de Evanston (Illinois), donde se graduó en 1971. Tras terminar sus estudios, realizó la prestación social sustitutoria (es objetor de conciencia), dirigió torneos de ajedrez y trabajó como profesor de periodismo en el instituto Clarke de Dubuque, Iowa (1976-1978). Fue un prolífico autor de obras cortas de ficción en los años 1970 y su obra fue premiada con varios premios Hugo y Nebula. Al final de esta década comenzó a publicar sus primeras novelas siendo una de las más populares la primera de ellas: Muerte de la luz (Dying of the Light, 1977). Dicho éxito le permitió dedicarse en exclusiva a la literatura, donde mezcla los géneros de ciencia ficción, fantasía y terror. En 1996 dejó Hollywood y se retiró a Santa Fe (Nuevo México), donde regresó al mundo de la literatura comenzando con la novela Juego de tronos (A Game of Thrones, 1996) el ciclo de novelas Canción de hielo y fuego, con la que ha obtenido gran éxito de crítica y ventas. En 2011 se casó con su antigua amante Parris McBride. En 2013 adquirió el cine Jean Cocteau de Santa Fe y el Coffee House, cerrado desde 2006, y los restauró y modernizó, transformando a este último en un café-museo con exposiciones itinerantes de arte. Ideológicamente demócrata, ha defendido siempre a los presidentes de este partido y sus políticas. Actualmente, está escribiendo el sexto libro de la saga Canción de hielo y fuego: Vientos de invierno. Esta saga de novelas es, sin duda, la que lo ha catapultado a lo más alto de su carrera como escritor.',
    'libros': ['Una canción pára Lía', 'Muerte de la luz', 'Juego de tronos, Canción de hielo y fuego', 'Juego de tronos, Choque de reyes', 'Juego de tronos, Tormenta de espadas', 'Juego de tronos, Vientos de invierno'],
    'imagenAutor': '/media/img/imgAutores/george_rr_martin.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Kerri Maniscalco',
    'nacimiento': '1983',
    'defuncion': '',
    'nacionalidad': 'Estadounidense',
    'bibliografia': 'Nacida en Newburgh, Nueva York, Kerri Maniscalco es una autora americana conocida por su saga A la caza de Jack el Destripador, una serie de thrillers góticos.   Maniscalco creció en Nueva York, ciudad donde estudió Bellas Artes antes de transferirse a Diseño de Comunicación en el Fashion Institute of Technology de Manhattan. Durante sus estudios, realizó cursos acerca de justicia criminal y ciencia, considerando formarse como psicóloga forense, opción que desechó por labrarse una carrera como escritora.    Su pasión por los libros es debida, en gran parte, al amor que le inculcó su abuela por la lectura, enseñándole la importancia de poder escapar de la realidad a través de ella.   Su primera obra, A la caza de Jack el Destripador, fue publicada en 2016, dando comienzo así a una serie bajo el mismo nombre.',
    'libros': ['El reino de los malditos', 'A la caza del diablo', 'A la caza de Houdini', 'A la caza del principe Drácula'],
    'imagenAutor': '/media/img/imgAutores/kerri_maniscalco.webp',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Jara Santamaría',
    'nacimiento': '1990',
    'defuncion': '',
    'nacionalidad': 'Española',
    'bibliografia': 'Jara Santamaría, nació el 10 de enero de 1990, en Zaragoza, España. Pasó su infancia en Pamplona. Estudió Periodismo y Comunicación Audiovisual en la Universidad Carlos III de Madrid. Es periodista y trabaja en el ámbito de la comunicación. Colabora en la revista digital Culturamas y en el blog de literatura juvenil de la librería Kirikú y la Bruja, además de participar en actividades de animación a la lectura.    En 2007 obtuvo el II Premio Jordi Sierra i Fabra para Jóvenes Escritores con la novela Te comerás el mundo, en 2016 la novela Londres después de ti, ganó el Premio Literario ”la Caixa”',
    'libros': ['Los dioses del norte,La leyenda del bosque', 'Te comeras el mundo', 'Londres despues de tí'],
    'imagenAutor': '/media/img/imgAutores/jara_santamaria.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Stephen King',
    'nacimiento': '1947',
    'defuncion': '',
    'nacionalidad': 'Estadounidense',
    'bibliografia': 'ucesor de sus compatriotas Edgar Allan Poe y Lovecraft, nacidos como él en la costa este de Estados Unidos, El Rey del Terror es uno de los autores más populares y prolíficos de la historia de la literatura.    Sus obras se han adaptado a todos los medios posibles, hasta el punto de convertirse en un icono cultural del siglo XX, además de un auténtico gigante de las letras contemporáneas. King nació en el pequeño estado de Maine, en el que ha pasado la mayor parte de su vida y que se convertiría en el escenario favorito de sus obras.    Su padre era marino mercante y, cuando el futuro escritor tenía dos años, abandonó a su familia, por lo que su madre Ruth se vio obligada de cuidar de él y de su hermano David, en una situación de gran precariedad económica, a la vez que trabajaba como cuidadora en una residencia para enfermos mentales.    Dos incidentes marcaron su infancia y, probablemente, su vocación literaria. El primero sería presenciar la trágica muerte de un amigo arrollado por un tren. Lo que le provocaría un estado de shock que derivo en amnesia y perdida de la habla temporal. El segundo fue el hallazgo de una colección de relatos de Lovecraft que había sido propiedad de su padre. King describió la lectura de ese libro como el hallazgo de su auténtico hogar.    En su adolescencia, durante los sesenta, comenzó a escribir relatos fantásticos y de terror que publicaba en fanzines y en el periódico del instituto. En 1970 se graduó en inglés en la Universidad de Maine. Para costear sus estudios, trabajó como conserje y en una lavandería industrial. En aquella época también conoció a su futura esposa, Tabitha, en la biblioteca de la universidad.    A partir de 1971, empezó a impartir clases de secundaria en el instituto de Hampden, otra localidad de Maine. Esa experiencia como docente inspiró su primera novela, Carrie. Es famosa la anécdota que tras concebirla como un cuento breve, desechó la historia y la tiró a la papelera. Tabitha encontró esas páginas, las leyó y lo convenció para continuarla. En 1973 Carrie fue adquirida por la editorial Doubleday. Tres años más tarde, sería llevada al cine por Brian de Palma.',
    'libros': ['Carrie', 'Christine', 'El ciclo del hombre lobo', 'La mitad oscura', 'Insomnia', 'El cazador de sueños', 'El bazar de los malos sueños', 'Doctor sueño'],
    'imagenAutor': '/media/img/imgAutores/stephen_king.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Edgar Allan Poe',
    'nacimiento': '1809',
    'defuncion': '1849',
    'nacionalidad': 'Estadounidense',
    'bibliografia': 'Edgar Allan Poe era hijo de Elizabeth Arlold Poe y David Poe, actores ambulantes de teatro, quienes lo dejaron huérfano a los dos años. Fue educado por John Allan, un acaudalado hombre de negocios de Richmond, y de 1815 a 1820 vivió con éste y su esposa en el Reino Unido, donde comenzó su educación.    Los Allan acogieron al niño, pero nunca lo adoptaron formalmente aunque le dieron el nombre de "Edgar Allan Poe".    Después de regresar a los Estados Unidos, Edgar Allan Poe siguió estudiando en centros privados y asistió a la Universidad de Virginia, pero en 1827 su afición al juego y a la bebida le acarreó la expulsión. Abandonó poco después el puesto de empleado que le había asignado su padre adoptivo, y viajó a Boston, donde publicó anónimamente su primer libro, Tamerlán y otros poemas.    Se enroló luego en el ejército, en el que permaneció dos años. En 1829 apareció su segundo libro de poemas, Al Aaraf, y obtuvo, por influencia de su padre adoptivo, un cargo en la Academia Militar de West Point, de la que a los pocos meses fue expulsado por negligencia en el cumplimiento del deber.    La miseria y el hambre lo acompañaron, por motivos económicos pronto dirigió sus esfuerzos a la prosa, escribiendo relatos y crítica literaria para algunos periódicos de la época; llegó a adquirir cierta notoriedad por su estilo cáustico y elegante. Debido a su trabajo, vivió en varias ciudades: Baltimore, Filadelfia y Nueva York.    En Baltimore, en 1835, contrajo matrimonio con su prima Virginia Clemm, que tenía tan sólo 13 años de edad. En enero de 1845, publicó un poema que lo haría célebre: "El cuervo". Su mujer murió de tuberculosis dos años más tarde. Aún hundido en la desolación, el autor terminó, en 1849, el poema "Eureka". Con la muerte de Virginia, Poe quedó devastado, su vida se fue en picada.    Falleció a tan sólo cuarenta años de edad, el 7 de octubre de 1849 en la ciudad de Baltimore. No se sabe el motivo exacto de su muerte, nunca fue aclarado. Se le atribuye a varias causas como el alcohol, las drogas, fallo cardíaco, rabia, suicidio, tuberculosis entre otras.    La impronta del escritor, tanto como su obra, marcó profundamente la literatura de su país y la de todo el mundo.',
    'libros': ['El Rey Peste', 'Ligeia', 'La caida de la casa de Usher', 'William Wilson', 'El escarabajo de oro', 'El demonio de la perversidad', 'El gato negro', 'Historias extraordinarias'],
    'imagenAutor': '/media/img/imgAutores/edgar_allan_poe.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Ed Warren',
    'nacimiento': '1926',
    'defuncion': '2006',
    'nacionalidad': 'Estadounidense',
    'bibliografia': 'Nació el 7 de septiembre de 1926 igualmente en Bridgeport, Connecticut. A diferencia de Lorraine, Ed comenzó a vivir experiencias paranormales entre los 5 y 12 años de edad. Entre las 2 o 3 de la mañana, cuando todos dormían, sucedieron una serie de hechos inexplicables. Ed narró en una entrevista de Secrets of the Supernatural que las puertas de su armario se abrían por sí solas, a los pocos segundos salían de él unas luces flotantes con rostros que lo miraban fijamente. Ed, antes de ser demonólogo, se dedicaba a pintar, algo que desde siempre le gustó y en lo que tenía talento. Pintaba especialmente cuadros de casas que ellos escuchaban que estaban "encantadas". Iban hasta el lugar y se sentaban en la orilla para poder tener una vista panorámica. Fue ahí cuando Lorraine empezó a desarrollar más su don: podía ver si la casa realmente estaba encantada o no, también podía ver qué es lo que había pasado y si eran fantasmas o algún ente demoníaco',
    'libros': ['La casa embrujada', 'El cementerio', 'En la oscuridad', 'Hombre lobo', 'Cazadores de fantasmas', 'La cosecha de satán'],
    'imagenAutor': '/media/img/imgAutores/ed_warren.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Natasha Preston',
    'nacimiento': '1988',
    'defuncion': '',
    'nacionalidad': 'Británica',
    'bibliografia': 'Nació en Inglaterra y creció y vivió en pequeñas ciudades y pueblos en el campo. Descubrió su pasión por la escritura cuando decidió publicar una historia en línea y desde entonces no ha parado de escribir.    Su etapa como escritora comenzó de manera accidental en 2010 al buscar en una tienda de aplicaciones y encontrar Wattpad, una plataforma en línea de lectura y escritura, donde los creadores pueden publicar novelas, relatos, poemas y muchos otros textos. Con este descubrimiento se animó a escribir y compartir sus historias de suspense cargadas de tensión y obtuvo un extraordinario éxito, tanto de seguidores como de lecturas completadas. Sus novelas se popularizaron gracias al boca a boca de su comunidad de lectores, y a día de hoy es un referente para los jóvenes escritores de suspenso. -Se le considera como uno de los tres grandes éxitos de Wattpad.    Su éxito en esta plataforma llamó la atención de editoriales tradicionales y logró publicar en 2014 “El sótano”, su primer libro en papel y desde entonces no dejó de publicar libros. Muchos de sus libros son número uno en New York Times y los más vendidos en las listas de Amazon e iBooks. El sótano estuvo 18 semanas en la lista de libros de bolsillo del New York Times mientras que “La Cabaña” pasó 17 semanas. Tiene numerosas novelas publicadas en el Reino Unido, Estados Unidos y Europa.   También cuenta con novelas románticas. Entre ellas se encuentran la trilogía Silence y The One aunque dispone de muchos títulos más.    Las claves del éxito de Preston para ganar la popularidad de la audiencia son un ritmo adictivo, giros inesperados, personajes adolescentes con los que es fácil identificarse y un toque morboso    Antes de su triunfo como escritora trabajó como administrativa y recepcionista.    Está casada y tiene dos hijos, Ashton y Remy.',
    'libros': ['El sótano', 'La cabaña', 'El anónimo', 'El despertar', 'La gemela'],
    'imagenAutor': '/media/img/imgAutores/natasha_preston.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Laura Freudenthaler',
    'nacimiento': '1984',
    'defuncion': '',
    'nacionalidad': 'Austriaca',
    'bibliografia': 'Laura Freudenthaler es una escritora austriaca. Estudió lengua y literatura alemanas en la universidad. Publicó un libro de cuentos titulado Der Schädel der Madeleine en 2014. También ha publicado dos novelas: Die Königin schweigt y Geistergeschichte. Ella vive en Viena',
    'libros': ['Opowiesc o duchach', 'Historia de fantasmeas'],
    'imagenAutor': '/media/img/imgAutores/laura_freudenthaler.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'George Orwell',
    'nacimiento': '1903',
    'defuncion': '1950',
    'nacionalidad': 'Británico',
    'bibliografia': 'ic Arthur Blair (Motihari, Raj Británico, 25 de junio de 1903-Londres, Reino Unido, 21 de enero de 1950), más conocido por su seudónimo de George Orwell, fue un novelista, periodista, ensayista y crítico británico nacido en la India, conocido mundialmente por su novelas distópicas Rebelión en la granja (1945) y 1984 (1949).   Su obra lleva la marca de las experiencias autobiográficas vividas por el autor en tres etapas de su vida: su posición en contra del imperialismo británico que lo llevó al compromiso como representante de las fuerzas del orden colonial en Birmania durante su juventud; a favor del socialismo democrático, después de haber observado y sufrido las condiciones de vida de las clases sociales de los trabajadores de Londres y París; y en contra de los totalitarismos nazi y estalinista tras su participación en la guerra civil española.    Además de cronista, crítico de literatura y novelista, es uno de los ensayistas en lengua inglesa más destacados de las décadas de 1930 y de 1940. Sin embargo, es más conocido por sus críticas al totalitarismo en su novela corta alegórica Rebelión en la granja (1945) y su novela distópica 1984 (1949), escrita en sus últimos años de vida y publicada poco antes de su fallecimiento, y en la que crea el concepto de «Gran Hermano», que desde entonces pasó al lenguaje común de la crítica de las técnicas modernas de vigilancia.    En 2008 figuraba en el puesto número dos del listado de los cincuenta escritores británicos de mayor relevancia desde 1945, elaborado por The Times.    El adjetivo «orwelliano» es frecuentemente utilizado en referencia al distópico universo totalitario imaginado por el escritor británico.',
    'libros': ['Los días de Birmania', 'La hija del clérigo', 'Subir a por aire', 'Rebelión en la granja', '1984'],
    'imagenAutor': '/media/img/imgAutores/george_orwell.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Lewis Carrol',
    'nacimiento': '1832',
    'defuncion': '1898',
    'nacionalidad': 'Británico',
    'bibliografia': 'Fue el mayor de los once hijos de Frances Jane Lutwidge y Charles Dodgson, un pastor protestante, cuatro varones y siete niñas, todos ellos tartamudos. Padeció varias enfermedades, una de las cuales lo dejó sordo de un oído. Asistió a la Escuela de Richmond, Yorkshire (1844-1845), y más tarde a la Escuela de Rugby (1846-1850). Cursó estudios en la Universidad de Oxford donde obtuvo el grado de bachiller y se recibió de preceptor.  Fue ordenado diácono de la Iglesia Anglicana en 1861 y enseñó Matemáticas, de 1855 a 1881. Su tartamudez y sus dudas doctrinales no fueron los únicos obstáculos que le impidieron entrar al sacerdocio. Su profesión de matemático le gustaba, aun cuando no destacase extraordinariamente como tal y, además, se resistía a someterse a ciertas reglas impuestas por la costumbre a los que se ordenaban sacerdotes. Por ejemplo, no hubiera podido asistir al teatro y estaba decidido a no abandonar este entretenimiento. Aunque se dedicó sobre todo a la geometría, escribió también sobre otros temas matemáticos: álgebra, cuadratura del círculo, cifrado de mensajes, lógica, etc. produciendo casi una docena de libros.   Padeció de insomnios durante toda su vida y pasaba noches enteras despierto. Escribió diversos libros sobre la materia y el más interesante de ellos se titula: Euclides y sus modernos rivales.    Desde los trece años y junto a sus hermanos, se dedicó a la publicación de pequeñas revistas literarias que él mismo redactaba y en ocasiones también ilustraba, para el uso de los invitados del presbítero de Croft (Yorkshire) donde ejercía su padre.    Publicó una colección de poesías con el título de Phantasmagoria and Other Poems en 1869, y otro poema largo, The Hunting of the Snark (La Caza del Snark) en 1876.    Con su verdadero nombre, Dodgson, publicó numerosas obras de matemáticas y un tratado de lógica del que solamente llegará a publicar la primera parte en 1896.',
    'libros': ['Alicia en el país de las maravilas', 'la caza del Snark', 'Silvia y Bruno', 'A través del espejo y Lo que Alicia encontró allí'],
    'imagenAutor': '/media/img/imgAutores/lewis_carroll.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'William Shakespeare',
    'nacimiento': '',
    'defuncion': '',
    'nacionalidad': 'Británico',
    'bibliografia': 'Hijo de una conocida familia de Stratford-upon-Avon, William Shakespeare nació en abril de 1564. No se conoce la fecha exacta de su nacimiento, aunque se cree que fue alrededor del día 26 de ese mes gracias a que se conserva su acta bautismal.   Shakespeare fue el tercero de los ochos hijos del matrimonio formado por John Shakespeare, político local y comerciante, y de Mary Arden. A pesar de la situación privilegiada que tenían, poco después del nacimiento del escritor todo cambió. Su familia fue perseguida, se cree, por profesar la fe católica.    Poco se sabe de la infancia y de la adolescencia del famoso escritor inglés. Todo apunta a que cursó los estudios primarios en una escuela local, la Stratford Grammar School. Sin embargo, no hay ningún documento que acredite que Shakespeare se formara allí ni cuántos años estudió.   En noviembre de 1582, William Shakespeare, de 18 años, contrajo matrimonio con Anne Hathaway, de 26. Con ella, el dramaturgo tuvo tres hijos: Susanna y los mellizos Judith y Hamnet. Este último murió a los once años por causas que se desconocen.    Los bautizos de sus tres hijos fueron los últimos datos que se tuvieron de Shakespeare durante unos diez años. Esto es lo que se conoce como “los años perdidos”.  Alrededor de 1590, William Shakespeare se trasladó a Londres y dejó a su familia en Stratford. Hay quien afirma que el escritor británico huyó para escapar de una condena por caza furtiva de ciervos. Sin embargo, no se tiene constancia de que fuera cierto.    Los comienzos en la capital inglesa fueron humildes. Muchos creen que trabajó como maestro y como aprendiz de carnicero antes de convertirse en el reconocido escritor que fue.   Hacia 1592, comenzó su andadura como dramaturgo y actor, trabajando en la compañía de teatros Chamberlains Men, de la que fue copropietario más tarde.   Tras la muerte de la reina Isabel I de Inglaterra en 1603, la compañía consiguió una patente real del rey Jacobo I de Inglaterra y VI de Escocia. A partir de ese momento, pasó a llamarse Kings Men.',
    'libros': ['El sueño de una noche de verano', 'Romeo y Julieta', 'Hamlet', 'Mcbeth'],
    'imagenAutor': '/media/img/imgAutores/william_shakespeare.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Gabriel García Márquez',
    'nacimiento': '1927',
    'defuncion': '2014',
    'nacionalidad': 'Colombiano',
    'bibliografia': 'Nace y pasa sus primeros años en una zona caribeña del norte de Colombia, que le marca especialmente por su contraste con Bogotá y otras zonas del país en las que vive más tarde. En 1947 empieza a estudiar Derecho, carrera que abandona para dedicarse al periodismo. Sus primeros artículos se publican en El Espectador y en El Heraldo y pasa a integrar el conocido como “Grupo de Barranquilla”, de cuya mano conoce la obra de los autores que más adelante le influenciarán: Faulkner, Virginia Woolf, Hemingway y Kafka, entre otros. Su primera obra, La hojarasca, se publica en 1955. En esa misma fecha viaja a Europa por primera vez y se queda allí cuatro años, viviendo en Ginebra, Roma y París. Durante su estancia en Francia, donde atraviesa dificultades económicas, escribe El coronel no tiene quien le escriba y La mala hora (publicadas en 1961 y 1962, respectivamente). Regresa a América en 1958 y se instala temporalmente en Venezuela, donde compagina una intensa actividad periodística con la escritura de los relatos de Los funerales de la Mamá Grande (1962). Tras pasar unos meses en Cuba, donde acaba de triunfar la revolución, y vivir un tiempo en Nueva York como corresponsal, decide establecerse en México. Allí trabaja en publicidad y escribe su primer guión para el cine, El gallo de oro, en colaboración con Carlos Fuentes.    Unos años después, en 1967, publica la que pronto se convierte en su obra más conocida, y a cuya escritura dedica más de un año de intenso trabajo: Cien años de soledad. El éxito es inmediato, agotándose la primera edición en apenas unos días, y para alejarse de la fama decide ir a Barcelona, donde vive de 1968 a 1974. Allí escribe El otoño del patriarca (publicado en 1975) y cuentos como Isabel viendo llover en Macondo (1968) o Relato de un náufrago (1970).  En los años sucesivos alterna su residencia entre México, Cartagena de Indias, La Habana y París. En 1982 recibe el Premio Nobel de Literatura y más adelante escribe El amor en los tiempos del cólera (1985), El general en su laberinto (1989) y Doce cuentos peregrinos (1992). En ese tiempo participa también en la fundación de la Escuela de Cine de San Antonio de los Baños (Cuba), donde dirige anualmente un taller de guión.    Muere en México D.F. el 17 de abril de 2014. Los herederos de Gabriel García Márquez depositaron el 24 de febrero de 2015 en la Caja de las Letras del Instituto Cervantes un legado del escritor in memoriam.',
    'libros': ['El coronel no tiene quien le escriba', 'La mala Hora', 'Relato de un naufrago', 'Del amor y otros demonios', 'Cien años de soledad'],
    'imagenAutor': '/media/img/imgAutores/gabriel_garcia_marquez.jpg',
    'nobel': true,
    'annoNobel': 1982
}, {
    'nombre': 'Rómulo Gallegos',
    'nacimiento': '1884',
    'defuncion': '1969',
    'nacionalidad': 'Venezolano',
    'bibliografia': 'El inicio de Rómulo Gallegos como escritor está asociado al teatro. Junto a sus compañeros de la revista La Alborada compartió la pasión por este género. Llegó a escribir varias obras, como «Los ídolos» (1909) y «El motor» (1910), de las cuales solo esta última se publicó en vida del autor. «Los ídolos» fue una pieza de la cual hizo una versión probablemente del mismo año, «Los predestinados» (la primera permanece inédita; la segunda fue publicada en el n.° 2 de La Alborada, el 14/2/1909). En las «Obras selectas», Editorial Edime, 1959, aparece «El motor» y «El milagro del año» de 1915, que también publicó como cuento. Gallegos hace referencias en diferentes momentos de obras de teatro que tenía en proyectos, o que destruyó, como lo es el caso de «Listos» (que refiere en carta a su amigo Salustio González) y «La espera» (probablemente de 1915). Su experiencia como dramaturgo luego se mostrará en el cine con el guion de «Doña Bárbara» (1940), y de «La Trepadora», «Canaima» y «La Señora del frente», para la industria mexicana. También en «Juan de la Calle» (1941). Casi ninguno de sus guiones se conserva. Salvo una pieza en 32 actos llamada «La doncella», que se publicó en México en 1957. Se trata de una emocionante pieza sobre la vida de Juana de Arco, y donde su maestría del diálogo se muestra con fuerza, pero no se llevó a cabo su rodaje pese a que era un encargo.  En sus comienzos como narrador, Rómulo Gallegos publicó Los Aventureros (Caracas, 1913), una colección de cuentos. Otros relatos son recopilados en La Rebelión y otros cuentos (Caracas, 1946), La Doncella y El Último Patriota (México, 1957). Su período como cuentista abarca desde 1913 hasta 1919, aunque otros cuentos se publicarán en 1922. En sus obras siempre mantendrá el realismo, las cuales se dividen en tres temáticas fundamentales: Los de crítica de costumbres, los de ambiente criollo donde plantea la antinomia civilización y barbarie, y los que describen pasiones, desequilibrios y anormalidades.',
    'libros': ['Reinaldo Solar', 'La trepadora', 'Doña Bárbara', 'Cantaclaro', 'Pobre Negro', 'La brizna de paja en el viento', 'Tierra bajo los pies'],
    'imagenAutor': '/media/img/imgAutores/romulo_gallegos.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Gabriela Mistral',
    'nacimiento': '1889',
    'defuncion': '1957',
    'nacionalidad': 'Chilena',
    'bibliografia': 'Su verdadero nombre es Lucila de María del Perpetuo Socorro Godoy Alcayaga, más conocida por su seudónimo Gabriela Mistral, utilizado por primera vez en el poema «Del pasado» publicado en diario «El Coquimbo» en 1908. Trabaja de maestra y colabora en publicaciones literarias, apareciendo sus primeros escritos en 1904 en: «El Coquimbo», «Penumbras de La Serena» y «La Voz de Elqui de Vicuña».  Durante esta etapa empieza a escribir «Desolación» y colabora con la revista «Elegancias», que dirige Rubén Darío desde París. En 1914 obtiene el Premio Nacional de Poesía de Chile con «Sonetos de la muerte».   En 1922 se traslada a México para colaborar en los planes de reforma educativos de José Vasconcelos, político, pensador y escritor mexicano. En este país, en 1923 se publica «Lecturas para mujeres», y en Barcelona, la antología «Las mejores poesías». En 1924, invitada por el gobierno mexicano, viaja por Estados Unidos y Europa.    En 1925 es nombrada secretaria del Instituto de Cooperación Intelectual de la Sociedad de Naciones en Ginebra (Suiza) y asiste a distintos congresos por Suiza. En 1928 representa a Chile y Ecuador en el Congreso de la Federación Internacional Universitaria en Madrid, y trabaja en el Consejo Administrativo del Instituto Cinematográfico Educativo de la Liga de las Naciones, en Roma (Italia).    Durante la década de los 30, da clases en Estados Unidos en las escuelas Bernard College,  Vassar College y en el Middlebury College. También viaja por Centroamérica y Las Antillas y colabora con las universidades de Puerto Rico, La Habana y Panamá. En 1933 es nombrada cónsul de Chile en Madrid, y en 1934 se la nombra hija adoptiva en Puerto Rico. Durante este periodo como embajadora, viaja por Lisboa, Guatemala, Francia, Brasil, Estados Unidos, México e Italia.  En 1938 aparece su libro de poesía «Tala» publicado en Buenos Aires, dedicado a los niños españoles víctimas de la Guerra Civil.   El 10 de diciembre de 1945 recibe el Nobel de Literatura, en 1950 el premio Serra de las Américas de la Academy of American Franciscan History de Washington y en 1951 el Premio Nacional de Literatura de Chile. En 1953 es nombrada cónsul en Nueva York y también delegada de la Asamblea General de Naciones Unidas.',
    'libros': ['Sonetos de la muerte', 'Desolación', 'Ternura', 'Tala', 'lagar'],
    'imagenAutor': '/media/img/imgAutores/gabriela_mistral.jpg',
    'nobel': true,
    'annoNobel': 1945
}, {
    'nombre': 'Isabel Allende',
    'nacimiento': '1942',
    'defuncion': 'Hija del diplomático chileno Tomás Allende Pesceque quien le inculcó su afición por las letras. Nació en Lima mientras su padre se desempeñaba como embajador de Chile en Perú.    Isabel Allende cursó estudios de periodismo. Mientras se iniciaba en la escritura de obras de teatro y cuentos infantiles, trabajó como redactora y columnista en la prensa escrita y la televisión.    En 1960 Isabel Allende entró a formar parte de la sección chilena de la FAO, la organización de las Naciones Unidas que se ocupa de la mejora del nivel de vida de la población mediante un exhaustivo aprovechamiento de las posibilidades de cada zona.   En 1962 contrajo matrimonio con Miguel Frías, del que habría de divorciarse en 1987, después de haber tenido dos hijos: Paula -que falleció, víctima de porfiria, en 1992- y Nicolás. En 1973, tras el golpe militar chileno encabezado por el general Pinochet, en el que murió su tío, el presidente Salvador Allende, abandonó su país y se instaló en Caracas, donde inició su producción literaria. La casa de los espíritus (1982), es su primera novela y su obra más conocida. Más tarde fue adaptada tanto al cine con el mismo título por Bille August como al teatro. Autora de superventas, la tirada total de sus libros alcanza 57 millones de ejemplares y sus obras han sido traducidas a 35 idiomas; está considerada como la escritora viva de lengua española más leída del mundo.',
    'nacionalidad': 'Peruana',
    'bibliografia': '',
    'libros': ['De amor y de sombra', 'Retrato en sepia', 'La isla bajo el mar', 'La ciudad de las bestias', 'Violeta', 'El reino del dragón de oro', 'Largo pétalo de mar'],
    'imagenAutor': '/media/img/imgAutores/isabel_allende.JPG',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Pablo Neruda',
    'nacimiento': '1904',
    'defuncion': '1973',
    'nacionalidad': 'Chileno',
    'bibliografia': 'Ricardo Eliecer Neftalí Reyes Basoalto, Pablo Neruda, nació el 12 de julio de 1904 en la ciudad de Parral, ubicada en la región central de Chile.  Fue el unigénito hijo de la maestra Rosa Basoalto, a quien no conoció porque murió de tuberculosis poco tiempo después de dar a luz, y del conductor de ferrocarril José del Carmen Reyes Morales, quien dos años después se radicaría en Temuco con el niño y donde contraería matrimonio por segunda vez con Trinidad Cambia Marverde, a quien Neruda le dedicaría uno de sus poemas. En 1910, Neruda ingresa al Liceo de Hombres, donde cursa todos sus estudios hasta terminar el 6º año de humanidades en 1920. El impresionante entorno natural de Temuco, sus bosques, lagos, ríos y montañas marcarán para siempre el mundo poético de Neruda.  En 1917, publica su primer artículo en el diario La Mañana de Temuco, con el título de Entusiasmo y perseverancia. En esta ciudad escribió gran parte de los trabajos, que pasarían a integrar su primer libro de poemas: Crepusculario.    Alrededor de 1920, conoce a Gabriela Mistral, de cuyo encuentro recordará: «...ella me hizo leer los primeros grandes nombres de la literatura rusa que tanta influencia tuvieron sobre mí». Hacia 1921 y con diecisiete años de edad, empieza firmar definitivamente sus escritos con el seudónimo de Pablo Neruda, fundamentalmente con el fin de soslayar el disgusto del padre por tener un hijo poeta.   En 1924 publicó su famoso `Veinte poemas de amor y una canción desesperada, en el que aún se nota un influjo del modernismo. Luego se revela un determinación de renovación formal, de intención vanguardista, en tres breves libros publicados en 1926: El habitante y su esperanza, Anillos (en colaboración con Tomás Lago) y Tentativa del hombre infinito.  En 1927, dio comienzo su extensa carrera diplomática siendo cónsul en Rangún, Birmania, desde donde se acrecenta un memorable epistolario con el escritor argentino Héctor Eandi. Será luego cónsul en Sri Lanka, Java, Singapur, Buenos Aires, Barcelona y Madrid.En la cima de su popularidad y prestigio fue sorprendido por el golpe militar del 11 de septiembre de 1973, contra el presidente Salvador Allende. La nueva situación de su país lo afecta profundamente y su salud se resiente aún más debido a un cáncer de próstata que lo aquejaba. Razón por la cual, es trasladado de urgencia desde su casa de Isla Negra a Santiago, donde fallece el 23 de septiembre de 1973. ',
    'libros': ['Crepusculario', 'Veinte poemas de amor y una canción desesperada', 'El habitante y su esperanza', 'Todo el amor', 'Odas elementales', 'Memorial de Isla Negra', 'Fulgor y muerte de Joaquín Murieta', 'La rosa separada', 'Tentativa del hombre infinito'],
    'imagenAutor': '/media/img/imgAutores/pablo_neruda.jpg',
    'nobel': true,
    'annoNobel': 1971
}, {
    'nombre': 'Isaac Asimov',
    'nacimiento': '1920',
    'defuncion': '1992',
    'nacionalidad': 'Estadounidense',
    'bibliografia': 'Isaac Asimov fue un escritor y profesor de bioquímica en la facultad de medicina de la universidad de Boston de origen ruso, nacionalizado estadounidense, conocido por ser un prolífico autor de obras de ciencia ficción, historia y divulgación científica.    Su obra más famosa es la Serie de la Fundación, también conocida como Trilogía o Ciclo de Trántor, que forma parte de la serie del Imperio Galáctico y que más tarde combinó con su otra gran serie sobre los robots. También escribió obras de misterio y fantasía, así como una gran cantidad de textos de no ficción. En total, firmó más de 500 volúmenes y unas 9000 cartas o postales. Sus trabajos han sido publicados en 9 de las 10 categorías del Sistema Dewey de clasificación.    Junto con Robert A. Heinlein y Arthur C. Clarke, Asimov fue considerado en vida como uno de los «tres grandes» escritores de ciencia ficción.    La mayoría de sus libros de divulgación explican los conceptos científicos siguiendo una línea histórica, retrotrayéndose lo más posible a tiempos en que la ciencia en cuestión se encontraba en una etapa elemental. A menudo brinda la nacionalidad, las fechas de nacimiento y muerte de los científicos que menciona, así como las etimologías de las palabras técnicas.   Fue miembro de Mensa durante mucho tiempo, a cuyos miembros describía como «intelectualmente combativos». Disfrutaba más de la presidencia de la Asociación Humanista Estadounidense, una organización de ideología atea.    En 1981 se nombró a un asteroide, el (5020) Asimov, en su honor.',
    'libros': ['Yo, robot', 'Sueños de robot', 'Azazel', 'Fundación e imperio', 'El sol desnudo', 'Asesinato en la convención', 'Los límites de la fundación', 'Los robots del amanecer'],
    'imagenAutor': '/media/img/imgAutores/isaac_asimov.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'H.G. Wells',
    'nacimiento': '1866',
    'defuncion': '1946',
    'nacionalidad': 'Británico',
    'bibliografia': ' H. G. Wells, fue un escritor y novelista británico. Wells fue un autor prolífico que escribió en diversos géneros, como ciencia ficción, docenas de novelas, relatos cortos, obras de crítica social, sátiras, biografías y autobiografías. Es recordado por sus novelas de ciencia ficción y es frecuentemente citado como el «padre de la ciencia ficción» junto con Julio Verne y Hugo Gernsback.    Sin embargo, durante su vida fue reconocido como un crítico social con visión de futuro, incluso profético, que dedicó sus talentos literarios al desarrollo de una visión progresista a escala global. En su faceta de futurista, escribió diversas obras utópicas y previó el advenimiento de aviones, tanques, viajes espaciales, armas nucleares, televisión por satélite y algo parecido a internet. En la ciencia ficción imaginó viajes en el tiempo, invasiones alienígenas, invisibilidad e ingeniería biológica. Entre sus obras más destacadas están La máquina del tiempo (1895), La isla del doctor Moreau (1896), El hombre invisible (1897), La guerra de los mundos (1898) y La guerra en el aire (1907). Estuvo nominado en cuatro ocasiones al Premio Nobel de Literatura.    En un principio Wells estudió biología y sus ideas sobre cuestiones éticas se desenvolvieron en un contexto específica y fundamentalmente darwiniano. También fue siempre un abierto socialista que a menudo (aunque no siempre, como al comienzo de la Primera Guerra Mundial) simpatizó con posturas pacifistas. Sus obras posteriores fueron cada vez más políticas y didácticas, dejando de lado la ciencia ficción, mientras que a veces indicaba en documentos oficiales que su profesión era el periodismo. Novelas como Kipps o La historia de Mr. Polly, que describen la vida de la clase media-baja, llevaron a sugerir que era un digno sucesor de Charles Dickens, aunque Wells retrató numerosos estratos sociales e incluso intentó, en Tono-Bungay (1909), un diagnóstico del conjunto de la sociedad inglesa. Enfermo de diabetes, Wells cofundó en 1934 La Asociación Diabética (hoy conocido como Diabetes UK), de finalidad caritativa. Por sus escritos relacionados con la ciencia, en 1970 se decidió en su honor llamar H. G. Wells a un astroblema lunar ubicado en la cara oculta de la Luna.',
    'libros': ['La máquina del tiempo', 'La isla del doctor Moreau', 'El hombre invisible', 'la guerra de los mundos'],
    'imagenAutor': '/media/img/imgAutores/H.G._Wells.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'J.J. Benítez',
    'nacimiento': '1946',
    'defuncion': '',
    'nacionalidad': 'Español',
    'bibliografia': 'Estudió en la Universidad de Navarra la carrera de periodismo y consiguió la licenciatura en 1965. Comenzó a trabajar para el periódico La Verdad de Murcia en enero de 1966. Después pasó al periódico Heraldo de Aragón. Recorrió el mundo como enviado especial y fue periodista en varios diarios regionales españoles.    Más tarde se traslada a Bilbao, donde continúa como periodista para La Gaceta del Norte. A partir de 1974, se especializa en el tema ovni y cubre todas las noticias relacionadas con esta materia para su periódico, destacando las primeras de las cuales fueron sobre la Fuerza Aérea Española. En 1975, realiza investigaciones sobre el sudario de Turín, hecho que marcó su vida al dar origen a la serie de novelas Caballo de Troya, sobre la visión de Benítez acerca de la vida de Jesús de Nazaret. En el epílogo de la primera novela, afirma que es el primer libro donde introduce ficción (refiriéndose al viaje en el tiempo) en una obra que refleja sus investigaciones. Sin embargo, voces críticas manifiestan que esta novela inspira y plagia relatos y ensayos de otros autores.    En una entrevista, Benítez señala que Jesucristo es «el Gran Extraterrestre». Además afirma: «Los lectores se van a encontrar con el comienzo de su etapa como predicador, pero diferente a la versión oficial. Yo mismo me he sorprendido. Por ejemplo, lo que se conoce como la ceremonia del bautismo en el Jordán es más fascinante de lo que nos han contado, de que entró al agua y apareció una paloma. Lo de la paloma es un invento de los evangelistas».    En 1976 recibió de la mano del Teniente General Felipe Galarza, Jefe del Estado Mayor del Ejército del Aire Español, doce expedientes OVNI clasificados que Benítez publicaría íntegramente en su libro Ovnis: Documentos Oficiales del Gobierno Español (que posteriormente se reeditaría con el título Ovni: alto secreto). Fue la primera desclasificación de archivos OVNI en España después que en diciembre de 1968 fuera declarado el tema ovni como "Materia Reservada". En 1979 dejó el periodismo activo.    En octubre de 2006 se publicó la octava parte de la serie Caballo de Troya (Jordán). En 2010, y pese a que no suele prologar ningún libro, escribió el prólogo a Ovnis, alto secreto, el primer libro de su amigo Marcelino Requejo. En noviembre de 2011, publicó su último libro, Caballo de Troya 9: Caná, el último de la saga "Caballo de Troya".',
    'libros': ['Caballo de Troya 1 Jerusalem', 'Caballo de Troya 2 Masada', 'Caballo de Troya 3 Saidan', 'Caballo de Troya 4 Nazaret', 'Caballo de Troya 5 Cesárea'],
    'imagenAutor': '/media/img/imgAutores/jj_benitez.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Mary Shelley',
    'nacimiento': '1797',
    'defuncion': '1851',
    'nacionalidad': 'Británica',
    'bibliografia': 'Mary Wollstonecraft Godwin  fue una escritora dramaturga, ensayista y biógrafa británica reconocida principalmente por ser la autora de la novela gótica Frankenstein o el moderno Prometeo (1818), considerada la primera novela de ciencia ficción moderna y que logra inaugurar el género. También editó y promocionó las obras de su esposo, el poeta y filósofo romántico Percy Bysshe Shelley. Su padre fue el filósofo político William Godwin y su madre la filósofa Mary Wollstonecraft, escritora del libro fundacional del Feminismo "La Vindicación de los Derechos de la Mujer".   En 1814, Mary Godwin inició una relación sentimental con uno de los seguidores políticos de su padre, Percy Bysshe Shelley, quien ya estaba casado. Los dos, junto con la hermanastra de Mary, Claire Clairmont, vivieron en Francia y viajaron por Europa; a su regreso a Inglaterra, Mary estaba embarazada. Durante los siguientes dos años ella y Percy se enfrentaron al ostracismo social, a las deudas constantes y a la desgracia del fallecimiento de su hija, nacida prematuramente. Se casaron a finales de 1816, tras el suicidio de la primera esposa de Percy Shelley, Harriet.   En 1816, la pareja pasó un verano con George Gordon Byron, John William Polidori y Claire Clairmont cerca de Ginebra, Suiza, donde Mary concibió la idea para su novela Frankenstein. Los Shelley abandonaron Gran Bretaña en 1818 y se mudaron a Italia, donde su segundo y su tercer hijo murieron antes de que Shelley diese a luz a su último hijo, el único que sobrevivió, Percy Florence. En 1822, su esposo Percy Bysshe Shelley se ahogó al hundirse su velero, durante una tormenta en la Bahía de La Spezia. Un año después, Mary Shelley regresó a Inglaterra y desde entonces en adelante se dedicó a la educación de su hijo y a su carrera como escritora profesional. La última década de su vida estuvo plagada de enfermedades, probablemente vinculadas al tumor cerebral que acabaría con ella a los 53 años.    Hasta la década de 1970 Mary Shelley fue principalmente reconocida por sus esfuerzos para publicar las obras de Percy Shelley y por su novela Frankenstein, la cual sigue siendo ampliamente leída y ha inspirado varias adaptaciones en cine y teatro.',
    'libros': ['Frankenstein', 'Mathilda', 'Valperga', 'Perkin Warbeck'],
    'imagenAutor': '/media/img/imgAutores/mary_shelley.jpg',
    'nobel': false,
    'annoNobel': ''
}, {
    'nombre': 'Julio Verne',
    'nacimiento': '1828',
    'defuncion': '1905',
    'nacionalidad': 'Francés',
    'bibliografia': 'Fue el mayor de los cinco hijos que tuvo el matrimonio formado por Pierre Verne, que procedía de una familia vinculada a la jurisprudencia (su abuelo fue consejero notario de Luis XV y presidente del Colegio de Abogados de Nantes), y de Sophie Allotte de la Fuÿe, perteneciente a una familia de militares.   En 1847 comenzó sus estudios de derecho en París y se recibió de abogado en 1849, razón por la cual su padre le permite permanecer en París. Mientras tanto seguiría escribiendo teatro. A pesar de los deseos de su padre que quiso que se dedicara a su carrera de abogacía y ante la amenaza de quitarle el financiamiento, Verne sigue sin estar interesado en seguir esa la labor. Y ya sin el financiamiento de su padre, gasta todos sus ahorros en libros y se pasa largas horas en las bibliotecas de París queriendo saberlo todo: estudiando geología, ingeniería y astronomía, conocimientos con los que más adelante documentaría sus fantásticas aventuras y predijera con asombrosa exactitud muchos de los logros científicos del siglo XX. Hablaría de cohetes espaciales, submarinos, helicópteros, aire acondicionado, misiles dirigidos e imágenes en movimiento, mucho antes de que aparecieran estos inventos. Recién en 1869 publicaría su primera novela "Cinco semanas en Globo", un éxito fulminante, gracias al cual firmó un espléndido contrato con el editor P. J. Hetzel, que le garantizaría la cantidad anual de 20.000 francos durante los siguientes veinte años, a cambio de lo cual, se obligaría a escribir dos novelas de un nuevo estilo cada año. Luego le siguieron otras novelas a la gran producción del autor: "Viaje al centro de la tierra"(1864), "De la tierra a la luna"(1865), y "20,000 Leguas de viaje submarino"(1870). La última novela antes de su muerte fue "La invasión del mar".   Célebre por sus relatos de aventuras fantásticas, narradas siempre con un tono de verosimilitud científica, en las que describe, con una visión casi profética, multitud de logros científicos, inventos y descubrimientos posteriores a su época. Fue considerado el precursor de un género literario nuevo, la ciencia ficción.   Falleció en 1905 en la ciudad de Amines.',
    'libros': ['De la tierra a la luna', 'El faro del fin del mundo', 'las indias negras', 'Una ciudad flotante', 'Cinco semanas en globo', 'Veite mil leguas de viaje submarino', 'Viaje al centro de la tierra'],
    'imagenAutor': '/media/img/imgAutores/julio_verne.jpg',
    'nobel': false,
    'annoNobel': ''
}]