let lista_libros = [{
    'isbn': '978-99924-67-83-1',
    'titulo': 'Dos cabezas para meter un gol',
    'autor': 'Julio Serrano Echeverría',
    'genero': 'Infantil',
    'publicacion': 2021,
    'impreso': true,
    'digital': true,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/dos_cabezas_para_meter_un_gol.png',
    'stock': true,
    'precio': 8150,
    'descuento': 0,
    'infoLibro': 'Cuando teja su primer huipil a Luz le gustaría bordarle el escudo del Chajul FC, para recordar a su equipo favorito. Su abuela le dice que nunca se ha visto un huipil con un escudo de fútbol, pero le encanta ver correr a Luz tras la pelota con su corte rojo y sus tenis. Sin duda, los tiempos cambian.',
    'calificacion': 4,
    'premios': 'Finalista del Tercer Concurso Centroamericano de Literatura Infantil',
    'nobel': false
}, {
    'isbn': '978-99924-67-77-0',
    'titulo': 'El monstruo de mi closet',
    'autor': 'Guadalupe Castellanos',
    'genero': 'Infantil',
    'publicacion': 2019,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/el_mostruo_de_mi_closet.jpg',
    'stock': true,
    'precio': 6175,
    'descuento': 0,
    'infoLibro': 'El cuarto de Alex es un tremendo desorden y esta situación le provoca discusiones diarias con su mamá. Él intenta explicarle que no es su culpa, que es el monstruo que vive en su clóset, pero ¿quién puede creer semejante excusa? Álex se propone demostrar su inocencia y trama un arriesgado plan para atrapar al monstruo.Obra finalista en el 2.o Concurso Centroamericano de Literatura Infantil, promovido por ¡Libros para Niños!',
    'calificacion': 5,
    'premios': 'Obra finalista en el 2.o Concurso Centroamericano de Literatura Infantil',
    'nobel': false
}, {
    'isbn': '978-99924-67-81-7',
    'titulo': 'Los pájaros que volaron de cuadro',
    'autor': 'Sergio Ramírez',
    'genero': 'Infantil',
    'publicacion': 2019,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/Baja-Portada_Los_pjaros_que_volaron_del_cuadro.jpg',
    'stock': true,
    'precio': 9000,
    'descuento': 0,
    'infoLibro': 'La abuela estaba pintando un cuadro de pájaros. Buscando más luz, lo llevó al jardín y lo colocó debajo de un árbol de guayabas. En lo que entró a buscar más pinceles, los pájaros se escapan del cuadro en busca de frutas que no sepan a aceite y trementina. Los preocupados abuelos le piden a su nieta Mariana, que persuada a los pájaros a que regresen al lienzo. Sin embargo, no contaban con la astucia del impertinente ciertogüis',
    'calificacion': 5,
    'premios': 'Premio Fundación Cuatrogatos 2020',
    'nobel': false

}, {
    'isbn': '978-99924-67-75-6',
    'titulo': 'Canción de la noche en el mar',
    'autor': 'Rubén Dario',
    'genero': 'Infantil',
    'publicacion': 2016,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/cancion_de_la_noche_en_el_mar.jpg',
    'stock': true,
    'precio': 6500,
    'descuento': 0,
    'infoLibro': 'Un niño decide ir tras una luz que aparece en lo alto del cielo. Mientras se acerca, se pregunta si acaso la luz será un barco o un farol, un planeta o una estrella. ¿Será su imaginación?',
    'calificacion': 4,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-99924-67-80-0',
    'titulo': 'Los cuentos de tío Coyote y tío Conejo',
    'autor': 'Pablo Antonio Cuadra',
    'genero': 'Infantil',
    'publicacion': 2018,
    'impreso': true,
    'digital': true,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/Tio_Coyote_y_Tio_Conejo.jpg',
    'stock': true,
    'precio': 4550,
    'descuento': 0,
    'infoLibro': 'La obra contiene tres cuentos. Primero el episodio del tío Coyote, el tío Conejo, el “sandillal”, la Viejita y el Señor Obispo, donde el pobre tío Coyote se lleva la peor parte al ser quemado con un tizón; segundo la secuencia de la comilona de zapotes maduros para tío Conejo y zapotes celeques en perjuicio de la dentadura de tío Coyote; y por último, la trágica burla de tío Conejo contra tío Coyote al engañarlo para que se bebiera toda una poza porque en el fondo había un gran queso que no era más que la luna reflejada en el agua',
    'calificacion': 4,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84788-8-44-52',
    'titulo': 'Harry Potter y la Piedra Filosofal',
    'autor': 'Rowling, J.K.',
    'genero': 'Fantasía',
    'publicacion': 1999,
    'impreso': true,
    'digital': true,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/harry_potter_la_piedra_filosofal.jpg',
    'stock': true,
    'precio': 11500,
    'descuento': 0,
    'infoLibro': 'Harry Potter nunca conoció a sus padres. Desde bebé ha vivido con sus horribles tíos y primo, pero cuando está a punto de cumplir diez años, una serie de misteriosas y obstinadas cartas, y Hagrid, un gigantón bonachón, le desvelan que no es un niño normal: es un mago destinado a pasar a la historia; y que además irá a estudiar a Hogwarts, un colegio de magos. Allí conocerá a Ron y Hermione, de los que se hará amigo, y un secreto que pondrá en peligro su vida y la del resto de los hechiceros. ',
    'calificacion': 4,
    'premios': '',
    'nobel': false

}, {
    'isbn': '978-84450-0-06-63',
    'titulo': 'El señor de los anillos, La comunidad del anillo',
    'autor': 'J.R.R. Tolkien',
    'genero': 'Fantasía',
    'publicacion': 2012,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/El_senor_de_los_anillos_1.jpg',
    'stock': true,
    'precio': 15000,
    'descuento': 0,
    'infoLibro': 'En la adormecida e idílica Comarca, un joven hobbit recibe un encargo: custodiar el Anillo Único y emprender el viaje para su destrucción en la Grieta del Destino. Acompañado por magos, hombres, elfos y enanos, atravesará la Tierra Media y se internará en las sombras de Mordor, perseguido siempre por las huestes de Sauron, el Señor Oscuro, dispuesto a recuperar su creación para establecer el dominio definitivo del Mal.',
    'calificacion': 5,
    'premios': '',
    'nobel': false

}, {
    'isbn': '978-84962-0-89-64',
    'titulo': 'Juego de tronos, Canción de hielo y fuego',
    'autor': 'Geroge R.R. Martin',
    'genero': 'Fantasía',
    'publicacion': 2015,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/juego_de_tronos_1.jpg',
    'stock': true,
    'precio': 15000,
    'descuento': 0,
    'infoLibro': 'Canción de hielo y fuego: Libro primero La novela río más espectacular jamás escrita Tras el largo verano, el invierno se acerca a los Siete Reinos. Lord Eddard Stark, señor de Invernalia, deja sus dominios para unirse a la corte de su amigo el rey Robert Baratheon, llamado el Usurpador, hombre díscolo y otrora guerrero audaz cuyas mayores aficiones son comer, beber y engendrar bastardos. Eddard Stark ocupará el cargo de Mano del Rey e intentará desentrañar una maraña de intrigas que pondrá en peligro su vida y la de todos los suyos. En un mundo cuyas estaciones pueden durar decenios y en el que retazos de una magia inmemorial y olvidada surgen en los rincones más sombríos y maravillosos, la traición y la lealtad, la compasión y la sed de venganza, el amor y el poder hacen del juego de tronos una poderosa trampa que atrapará en sus fauces a los personajes... y al lector',
    'calificacion': 5,
    'premios': '',
    'nobel': false

}, {
    'isbn': '978-84178-5-43-31',
    'titulo': 'El reino de los malditos',
    'autor': 'Kerri Maniscalco',
    'genero': 'Fantasía',
    'publicacion': 2022,
    'impreso': true,
    'digital': true,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/el_reino_de_los_malditos.jpg',
    'stock': true,
    'precio': 6500,
    'descuento': 0,
    'infoLibro': 'Dos hermanas.Un despiadado asesinato.Una búsqueda de venganza que desatará el mismísimo infierno. Y un romance embriagador.Emilia y su hermana gemela Vittoria son streghe: brujas que viven en secreto entre los humanos, evitando llamar la atención y ser perseguidas. Pero una noche, Vittoria se pierde el turno de la cena en el famoso restaurante siciliano que regenta la familia. Y Emilia pronto encuentra el cuerpo de su querida gemela... profanado más allá de lo imaginable. Devastada, se propone encontrar al asesino de su hermana y conseguir venganza a cualquier precio, incluso si eso significa usar magia oscura, que lleva mucho tiempo prohibida.',
    'calificacion': 4,
    'premios': '',
    'nobel': false

}, {
    'isbn': '978-84174-2-43-43',
    'titulo': 'Los dioses del norte,La leyenda del bosque',
    'autor': 'Jara Santamaría',
    'genero': 'Fantasía',
    'publicacion': 2019,
    'impreso': true,
    'digital': true,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/los_dioses_del_norte.jpg',
    'stock': true,
    'precio': 10500,
    'descuento': 0,
    'infoLibro': 'Cuenta la leyenda que, en el valle del Baztán, los dioses convivían en hermandad y las criaturas del día y de la noche podían vivir en armonía. Pero Gaueko, el temible dios de la noche, empezó a atemorizar a los humanos con su séquito de lobos y la diosa de la tierra, Mari, engendró la Luna y el Sol para protegerlos de la oscuridad. Sin embargo, las ansias de poder de Gaueko le llevaron a tramar un plan para raptar al Sol y así instaurar de manera definitiva su reinado de las sombras. Presa de la ira, Mari dividió el mundo en dos y ya nada ni nadie pudo cruzar la frontera entre ambos.',
    'calificacion': 4,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84663-4-30-53',
    'titulo': 'El Bazar de los malos sueños',
    'autor': 'Stephen King',
    'genero': 'Terror',
    'publicacion': 2018,
    'impreso': true,
    'digital': true,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/el_bazar_de_los_malos_suenos.jpg',
    'stock': true,
    'precio': 16250,
    'descuento': 0,
    'infoLibro': 'Aunque han pasado ya treinta y cinco años desde que escribió su primera colección, Stephen King sigue deslumbrándonos con su maestría en el género. En esta ocasión trata temas como la moralidad, la vida después de la muerte, la culpa y lo que corregiríamos del pasado si pudiéramos ver el futuro',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84174-7-76-84',
    'titulo': 'Cuentos completos',
    'autor': 'Edgar Allan Poe',
    'genero': 'Terror',
    'publicacion': 2019,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/cuentos_completos_EAP.jpg',
    'stock': true,
    'precio': 10400,
    'descuento': 0,
    'infoLibro': 'El autor norteamericano Edgar Allan Poe (1809-1849) ocupa un lugar relevante en el panteón de los escritores más admirados, imitados y estudiados de la literatura universal. Considerado por muchos como un precursor del cuento corto y de terror como género literario, Edgar Allan Poe escribió también poesía, ensayos y crítica literaria. Aunque indudablemente fascinado con lo macabro y con un especial talento para ello, Poe también exploró diversos temas y tonos en su obra, con relatos detectivescos (de los cuales también es considerado pionero), humorísticos, históricos y hasta crónicas periodísticas. Su obra ha inspirado innumerables homenajes e influenciado el estilo de autores como H. P. Lovecraft y Arthur Conan Doyle. Con una vida marcada por la tragedia Poe logró dejar una huella indeleble en la historia literaria de su país y del mundo, como un maestro de la naturaleza humana y de todos sus matices. El presente volumen contiene más de sesenta cuentos, reuniendo todos los relatos publicados durante su corta y accidentada vida.',
    'calificacion': 4,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84911-1-47-03',
    'titulo': 'El cementerio',
    'autor': 'Ed Warren',
    'genero': 'Terror',
    'publicacion': 2019,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/el_cementerio.jpg',
    'stock': true,
    'precio': 11700,
    'descuento': 0,
    'infoLibro': 'Los fantasmas siempre están hambrientos y nadie sabe mejor que Ed y Lorraine Warren lo voraces que pueden llegar a ser. Durante años, este matrimonio de parapsicólogos se ha dedicado a viajar por el mundo tratando de desentrañar la verdad oculta detrás de los casos sobrenaturales más aterradores. Además de ayudar a numerosas familias, su actividad les ha permitido recopilar sorprendentes pruebas de sus encuentros con lo paranormal.',
    'calificacion': 4,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84082-1-47-31',
    'titulo': 'El sótano',
    'autor': 'Natasha Preston',
    'genero': 'Terror',
    'publicacion': 2019,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/el_sotano.jpg',
    'stock': true,
    'precio': 12000,
    'descuento': 0,
    'infoLibro': 'Lily es una de las perfectas y puras flores que Clover cuida en el sótano de su casa. Él junto a sus queridas Lily, Rose, Violet y Poppy forman una familia perfecta que trae la felicidad a sus vidas. Ellas son chicas rectas e impecables alejadas de la putrefacción del mundo moderno: son todo lo que Clover desea.',
    'calificacion': 4,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84-17743-28-4',
    'titulo': 'Historia de Fantasmas',
    'autor': 'Laura Freudenthaler',
    'genero': 'Terror',
    'publicacion': 2022,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': '',
    'imagenLibro': '/media/img/portadaLibros/historia_de_fantasmas.jpg',
    'stock': true,
    'precio': 10700,
    'descuento': 0,
    'infoLibro': 'Lo que empieza como un triángulo amoroso, o como una historia de traición conyugal se va tornando menos claro. ¿Es paranoia? ¿El hombre con el que vive Anne desde hace 20 años la está engañando con una jovencita? ¿O es todo un espejismo, la mente jugándole una mala pasada? Historia de fantasmas es una novela que explora la sutil frontera entre realidad y fantasía en un mundo donde los límites entre lo real y lo imaginario se desdibujan, y al final lo que nos queda es una historia de terror sobre los fantasmas que habitan en nuestro interior. La autora juega con una presencia real e imaginada al mismo tiempo y crea progresivamente una red de relaciones complejas que, por su propia naturaleza, acaban convirtiéndose en una pesadilla.',
    'calificacion': 4,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84998-9-09-44',
    'titulo': '1984',
    'autor': 'George Orwell',
    'genero': 'Clásicos',
    'publicacion': 2019,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/1984.jpg',
    'stock': true,
    'precio': 6500,
    'descuento': 0,
    'infoLibro': 'En el año 1984 Londres es una ciudad lúgubre en la que la Policía del Pensamiento controla de forma asfixiante la vida de los ciudadanos. Winston Smith es un peón de este engranaje perverso y su cometido es reescribir la historia para adaptarla a lo que el Partido considera la versión oficial de los hechos. Hasta que decide replantearse la verdad del sistema que los gobierna y somete.',
    'calificacion': 4,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84174-3-04-81',
    'titulo': 'Las mil y una noches',
    'autor': 'Anónimo',
    'genero': 'Clásicos',
    'publicacion': 2019,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/las_mil_y_una_noches.jpg',
    'stock': true,
    'precio': 9500,
    'descuento': 0,
    'infoLibro': 'Las mil y una noches es una recopilación de historias inspiradas por la tradición oral, cuya relevancia fue curiosamente marginal dentro del contexto de la literatura árabe medieval. No obstante, a ella le debemos la fascinación por lo oriental que surgió a partir del siglo XVIII gracias a estudiosos como Antoine Galland, el autor de la primera traducción al francés, o exploradores como Richard Francis Burton, que la tradujo al inglés respetando el alto contenido erótico de la obra.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84156-1-87-13',
    'titulo': 'Alicia en el país de las maravillas',
    'autor': 'Lewis Carroll',
    'genero': 'Clásicos',
    'publicacion': 2017,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/alicia_en_el_pais_de_las_maravillas.jpg',
    'stock': true,
    'precio': 15000,
    'descuento': 0,
    'infoLibro': 'Alicia en el país de las maravillas de Lewis Carroll (seudónimo de Charles Lutwidge Dodgson) se ha convertido con el paso del tiempo en uno de los grandes clásicos de la literatura universal. En sus páginas repletas de personajes y situaciones insólitos en un mundo onírico, Carroll desafía la lógica y el lenguaje, y juega con el absurdo. Esta edición recupera las ilustraciones originales que John Tenniel creó para la primera edición del libro en 1865.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84670-3-40-59',
    'titulo': 'El Cantar del Mio Cid',
    'autor': 'Anónimo',
    'genero': 'Clásicos',
    'publicacion': 2010,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/el_cantar_del_mio_cid.jpg',
    'stock': true,
    'precio': 9500,
    'descuento': 0,
    'infoLibro': 'Difundido por los juglares en plazas y castillos, el poema constituye, al tiempo, una exaltación de los grandes valores del honor y la libertad y un cuadro de costumbres de la época. Esta edición del Cantar del Mío Cid ofrece un recorrido por la emocionante labor de investigación cidiana que llevó a cabo Menéndez Pidal: las incógnitas sobre la autoría del poema, su fecha de creación, la realidad histórica a la que responde, etc.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84667-5-17-35',
    'titulo': 'Romeo y Julieta',
    'autor': 'William Shakespeare',
    'genero': 'Clásicos',
    'publicacion': 2006,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/Romeo_y_Julieta.jpg',
    'stock': true,
    'precio': 19500,
    'descuento': 0,
    'infoLibro': 'Una tragedia de amor juvenil, apasionado y sin límites. Su autor, William Shakespeare, nos presenta a dos familias -los Montesco y los Capuleto- grandes enemigos desde hace años.    Romeo Montesco conoce a Julieta en una fiesta organizada por su familia, los Capuleto. Romeo, que acude a la fiesta enmascarado, se acerca a Julieta. Surge entonces un amor apasionado entre los jóvenes de las dos familias rivales. El amor que dará lugar a un conflicto de fatales consecuencias para los amantes.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': ' 978-84975-9-22-08',
    'titulo': 'Cien años de soledad',
    'autor': 'Gabriel García Márquez',
    'genero': 'Latinoamericanos',
    'publicacion': 2003,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/cien_annos_de_soledad.jpg',
    'stock': true,
    'precio': 19500,
    'descuento': 0,
    'infoLibro': 'Cien años de soledad es una obra del escritor colombiano Gabriel García Márquez, se trata de uno de los libros en español más traducido y leído, en 1999 el diario Le Monde, lo incluyó en el puesto número 33 de su lista “los 100 libros del siglo”.   La historia se centra en la familia Buendía, durante seis generaciones, desde José Arcadio Buendía y su mujer Úrsula, pertenecientes a una de las familias fundadoras del pueblo donde se desarrolla la trama-Macondo- hasta la sexta, Aureliano Babilonia. Se encuentra enmarcada en el principio del S. XX y se puede apreciar la guerra entre liberales y conservadores en la que se ve envuelto el Coronel Aureliano Buendía, perteneciente a la segunda generación,  así como la llegada de los americanos a Macondo que instalan una bananera.',
    'calificacion': 5,
    'premios': ['Romulo Gallegos 1972', 'Premio al mejor libro extranjero (Prix du Meilleur Livre Étranger) en Francia en 1969'],
    'nobel': true
}, {
    'isbn': '978-84376-1-53-94',
    'titulo': 'Doña Bárbara',
    'autor': 'Rómulo Gallegos',
    'genero': 'Latinoamericanos',
    'publicacion': 2005,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/donna_barbara.jpg',
    'stock': true,
    'precio': 13000,
    'descuento': 0,
    'infoLibro': '"Doña Bárbara", en la que la llanura venezolana es el personaje central, es su obra de mayor éxito. En ella dramatiza el conflicto entre civilización y barbarie que a su parecer definía el ser de Venezuela y su realidad. El final feliz simboliza un futuro esperanzador para el país.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-95611-2-10-27',
    'titulo': 'Antología poética de Gabriela Mistral',
    'autor': ['Gabriela Mistral', 'Alfonso Calderón'],
    'genero': 'Latinoamericanos',
    'publicacion': 2017,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/antologia_poetica.jpg',
    'stock': true,
    'precio': 13000,
    'descuento': 0,
    'infoLibro': 'Selección de textos poéticos de Gabriela Mistral, preparada por Alfonso Calderón. Incluye poemas de todos los libros de la autora (Desolación, Tala, Ternura, Lagar y Poema de Chile). Incluye una “entrevista póstuma” preparada por el antologador sobre la base de la correspondencia y materiales de archivo, así como una nota con datos biográficos de la autora.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84010-2-74-75',
    'titulo': 'Violeta',
    'autor': 'Isabel Allende',
    'genero': 'Latinoamericanos',
    'publicacion': 2017,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/violeta.jpg',
    'stock': true,
    'precio': 14500,
    'descuento': 0,
    'infoLibro': 'Violeta viene al mundo un tormentoso día de 1920, siendo la primera niña de una familia de cinco bulliciosos hermanos. Desde el principio su vida estará marcada por acontecimientos extraordinarios, pues todavía se sienten las ondas expansivas de la Gran Guerra cuando la gripe española llega a las orillas de su país sudamericano natal, casi en el momento exacto de su nacimiento.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84979-3-30-56',
    'titulo': 'Veinte poemas de amor y una canción desesperada',
    'autor': 'Pablo Neruda',
    'genero': 'Latinoamericanos',
    'publicacion': 2004,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/20_poemas_de_amor.jpg',
    'stock': true,
    'precio': 13000,
    'descuento': 0,
    'infoLibro': '«Neruda significa un hombre nuevo en la América, una sensibilidad con la cual abre todo capítulo emocional americano. Su alta categoría arranca de su rotunda diferenciación.»Gabriela Mistral',
    'calificacion': 5,
    'premios': '',
    'nobel': true
}, {
    'isbn': '978-84350-1-83-64',
    'titulo': 'Yo, robot',
    'autor': 'Isaac Asimov',
    'genero': 'Ciencia Ficción',
    'publicacion': 2009,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/yo_robot.jpg',
    'stock': true,
    'precio': 11700,
    'descuento': 0,
    'infoLibro': 'Las paradojas que se plantean en estos relatos futuristas no son sólo ingeniosos ejercicios intelectuales sino sobre todo una indagación sobre la situación del hombre actual en relación con los avances tecnológicos y con la experiencia del tiempo.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84179-2-88-03',
    'titulo': 'La guerra de los mundos',
    'autor': 'H.G. Wells',
    'genero': 'Ciencia Ficción',
    'publicacion': 2020,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/la_guerra_de_los_mundos.jpg',
    'stock': true,
    'precio': 11700,
    'descuento': 0,
    'infoLibro': 'La Guerra de los Mundos” (1897) es una de las obras más famosas del autor inglés H. G. Wells (1866-1946). Una pequeña ciudad inglesa se ve de pronto invadida por Marcianos dispuestos a acabar con cualquier humano que se encuentre en su camino. Esta es la historia de cómo un hombre vive la invasión, cómo su mundo se ve afectado por ella y la reacción de aquellos que le rodean ante la maldad de los invasores. La novela es una de las primeras en explorar la temática de la humanidad contra una raza extraterrestre y se ha convertido en un clásico indiscutible de la ciencia ficción por ello. La presente edición contiene ilustraciones de Alvim Corrêa y está presentada en formato de 13,5 x 19 cms, con encuadernación tapa dura y marca páginas de hilo.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84080-4-20-37',
    'titulo': 'Caballo de troya 1 Jerusalem',
    'autor': 'J.J. Benítez',
    'genero': 'Ciencia Ficción',
    'publicacion': 2013,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/caballo_de_troya_1.jpg',
    'stock': true,
    'precio': 14500,
    'descuento': 0,
    'infoLibro': 'Tal como afirma el propio J. J. Benítez, «adelantar el argumento y la naturaleza de Caballo de Troya 1 es quebrar el desconcertante misterio que encierran sus páginas». Podemos apuntar, eso sí, que para la elaboración de esta obra, el autor se ha basado en una documentación real, depositada hace años en Estados Unidos. Una documentación que pone al descubierto multitud de datos nuevos sobre la figura y la obra de Jesús de Nazaret. Podemos asegurar que tal y como sospecha buena parte de la Humanidad- las grandes potencias ocultan muchos de sus proyectos espaciales y militares, y «Caballo de Troya» es una prueba más de ello. Podemos revelar, por ejemplo, que en 1973 las Fuerzas Aéreas norteamericanas, después de varios años de preparación y tras un sinfín de peripecias, ejecutaron en pleno corazón de Israel uno de sus proyectos «supersecretos» que fue bautizado, precisamente, como Operación Caballo de Troya. Pero no podemos avanzar al lector cómo se consiguió esa fascinante documentación «confidencial» por parte de J. J. Benítez, ni tampoco el asombroso desarrollo de la referida Operación y su desconcertante final. Sería romper el encanto de Caballo de Troya 1, primer libro testimonio del periodista y escritor navarro. En palabras del autor:«… será el futuro, como sucedió con Julio Verne, quien pondrá de manifiesto si este relato fue o no verídico.»',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84179-2-88-58',
    'titulo': 'Frankenstein',
    'autor': 'Mary Shelley',
    'genero': 'Ciencia Ficción',
    'publicacion': 2020,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/frankenstein.jpg',
    'stock': true,
    'precio': 6500,
    'descuento': 0,
    'infoLibro': 'Fruto de la imaginación Mary Shelley (1797-1851), la historia de Frankenstein fue concebida durante unas vacaciones con su esposo, también escritor, en la residencia de lord Byron, junto al lago de Ginebra en 1816, cuando para distraerse se propuso en el grupo de amigos, la idea de escribir una historia de fantasmas y aparecidos. Escrita en estilo epistolar, “Frankenstein” rebasó los límites de la propuesta inicial y consiguió convertirse en una obra maestra en forma de parábola que trata de la ciencia del bien y del mal, de la soberbia y responsabilidad del conocimiento y de la soledad de los monstruos.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}, {
    'isbn': '978-84678-6-09-55',
    'titulo': 'Viaje al centro de la tierra',
    'autor': 'Julio Verne',
    'genero': 'Ciencia Ficción',
    'publicacion': 2014,
    'impreso': true,
    'digital': false,
    'audio': false,
    'idioma': 'Español',
    'imagenLibro': '/media/img/portadaLibros/viaje_al_centro_de_la_tierra.jpg',
    'stock': true,
    'precio': 9600,
    'descuento': 0,
    'infoLibro': 'Viaje al centro de la Tierra es la segunda aventura imaginada por Julio Verne de una larga serie que, con más de cincuenta entregas, estaría escribiendo durante toda su vida.    Sin duda Verne tenía un espíritu aventurero que necesitaba salir de vez en cuando a darse una vuelta. En esta ocasión, el escritor francés, se encarna por partida doble en la persona del profesor Lidenbrock, un excéntrico científico alemán, y su sobrino Axel, joven aún y huérfano, aprendiz de geólogo, que vive bajo su protección. El objetivo de la aventura que les une a los dos es demostrar que se puede llegar hasta el mismísimo centro de la Tierra siguiendo las huellas de Arne Saknussemm, un antiguo escritor del siglo XVI, investigador y viajero, que dejó un manuscrito secreto con las claves para realizar la expedición.',
    'calificacion': 5,
    'premios': '',
    'nobel': false
}];