let listaUsuarios = [{
    'tipoUsuario': 1,
    'primerNombre': 'Luis',
    'segundoNombre': 'Fernando',
    'primerApellido': 'Corrales',
    'segundoApellido': 'Muñoz',
    'tipoIdentificacion': 'Cedula de identidad',
    'numeroIdentificacion': '1-0935-0944',
    'provincia': 'San Jose',
    'distrito': 'Desamparados',
    'canton': 'Desamaparados',
    'direccionExacta': 'Barrio San Roque, Condominio Porto Fino',
    'genero': 'Masculino',
    'fotoPerfil': '//imgs/FotoPerfil1',
    'correo': 'lcorralesm@ucenfotec.ac.cr',
    'contrasena': 'NoLimits2022#',
    'autorFavorito': ['autor1', 'autor2', 'autor3', 'autor4'],
    'generoFavorito': ['genero1', 'genero2', 'genero3', 'genero4'],
}, {

    'tipoUsuario': 2,
    'primerNombre': 'Berny',
    'segundoNombre': 'Fabricio',
    'primerApellido': 'Salgado',
    'segundoApellido': 'Ulloa',
    'tipoIdentificacion': 'Cedula de identidad',
    'numeroIdentificacion': '1-1833-0299',
    'provincia': 'Alajuela',
    'distrito': 'Delicias',
    'canton': 'Upala',
    'direccionExacta': 'Santa Clara',
    'genero': 'Masculino',
    'fotoPerfil': '//imgs/FotoPerfil1',
    'correo': 'bsalgadou@ucenfotec.ac.cr',
    'contrasena': 'NoLimits2022#',
    'autorFavorito': ['autor1', 'autor2', 'autor3', 'autor4'],
    'generoFavorito': ['genero1', 'genero2', 'genero3', 'genero4'],
}, {
    'tipoUsuario': 2,
    'primerNombre': 'Franco',
    'segundoNombre': 'Shi Ming',
    'primerApellido': 'Wang',
    'segundoApellido': 'Quo',
    'tipoIdentificacion': 'Cedula de identidad',
    'numeroIdentificacion': '1-11890-460',
    'provincia': 'Heredia',
    'distrito': 'San Francisco',
    'canton': 'Heredia',
    'direccionExacta': 'Cielorazo pvc Dai Yi S.A.',
    'genero': 'Masculino',
    'fotoPerfil': '//imgs/FotoPerfil1',
    'correo': 'fwang@ucenfotec.ac.cr',
    'contrasena': 'NoLimits2022#',
    'autorFavorito': ['autor1', 'autor2', 'autor3', 'autor4'],
    'generoFavorito': ['genero1', 'genero2', 'genero3', 'genero4'],
}, {
    'tipoUsuario': 2,
    'primerNombre': 'Joshua',
    'segundoNombre': 'Andrey',
    'primerApellido': 'Sotelo',
    'segundoApellido': 'Solis',
    'tipoIdentificacion': 'Cedula de identidad',
    'numeroIdentificacion': '1-1762-0779',
    'provincia': 'Limon',
    'distrito': 'Limon',
    'canton': 'Limon',
    'direccionExacta': 'Minisuper los corrales 2, 100 metros este, casa esquinera de dos pisos ',
    'genero': 'Masculino',
    'fotoPerfil': '//imgs/FotoPerfil1',
    'correo': 'jsotelos@ucenfotec.ac.cr',
    'contrasena': 'NoLimits2022#',
    'autorFavorito': ['autor1', 'autor2', 'autor3', 'autor4'],
    'generoFavorito': ['genero1', 'genero2', 'genero3', 'genero4'],
}, {
    'tipoUsuario': 2,
    'primerNombre': 'Moises',
    'segundoNombre': '',
    'primerApellido': 'Granados',
    'segundoApellido': 'Fonseca',
    'tipoIdentificacion': 'Cedula de Identidad',
    'numeroIdentificacion': '3-0522-0864',
    'provincia': 'Cartago',
    'distrito': 'San Rafael',
    'canton': 'Oreamuno',
    'direccionExacta': 'Pali Los Angeles, 250 metros este y 150 metros sur, urbanizacion toyogres',
    'genero': 'Masculino',
    'fotoPerfil': '//imgs/FotoPerfil1',
    'correo': 'mgranadosf@ucenfotec.ac.cr',
    'contrasena': 'NoLimits2022#',
    'autorFavorito': ['autor1', 'autor2', 'autor3', 'autor4'],
    'generoFavorito': ['genero1', 'genero2', 'genero3', 'genero4'],
}, {
    'tipoUsuario': 2,
    'primerNombre': 'Evelyn',
    'segundoNombre': 'del Carmen',
    'primerApellido': 'Palma',
    'segundoApellido': 'Reyes',
    'tipoIdentificacion': 'Cedula de identidad',
    'numeroIdentificacion': '1-0888-0657',
    'provincia': 'San Jose',
    'distrito': 'Pavas',
    'canton': 'Central',
    'direccionExacta': 'Rohrmoser, urbanizacion Roma Oeste, calle 120A, avenida 39, casa 125',
    'genero': 'Femenino',
    'fotoPerfil': '//imgs/FotoPerfil1',
    'correo': 'epalmar@ucenfotec.ac.cr',
    'contrasena': 'NoLimits2022#',
    'autorFavorito': ['autor1', 'autor2', 'autor3', 'autor4'],
    'generoFavorito': ['genero1', 'genero2', 'genero3', 'genero4'],
}, {
    'tipoUsuario': 2,
    'primerNombre': 'Alejandro',
    'segundoNombre': '',
    'primerApellido': 'Jimenez',
    'segundoApellido': 'Barquero',
    'tipoIdentificacion': 'Cedula de identidad',
    'numeroIdentificacion': '3-0451-0588',
    'provincia': 'Cartago',
    'distrito': 'Concepcion',
    'canton': 'La Union',
    'direccionExacta': 'Condominio La Floresta, casa 82b',
    'genero': 'Masculino',
    'fotoPerfil': '//imgs/FotoPerfil1',
    'correo': 'ajimenezb@ucenfotec.ac.cr',
    'contrasena': 'NoLimits2022#',
    'autorFavorito': ['autor1', 'autor2', 'autor3', 'autor4'],
    'generoFavorito': ['genero1', 'genero2', 'genero3', 'genero4'],
}];